var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.owns=function(p,u){return Object.prototype.hasOwnProperty.call(p,u)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(p,u,r){if(p==Array.prototype||p==Object.prototype)return p;p[u]=r.value;return p};$jscomp.getGlobal=function(p){p=["object"==typeof globalThis&&globalThis,p,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var u=0;u<p.length;++u){var r=p[u];if(r&&r.Math==Math)return r}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(p,u){var r=$jscomp.propertyToPolyfillSymbol[u];if(null==r)return p[u];r=p[r];return void 0!==r?r:p[u]};
$jscomp.polyfill=function(p,u,r,y){u&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(p,u,r,y):$jscomp.polyfillUnisolated(p,u,r,y))};$jscomp.polyfillUnisolated=function(p,u,r,y){r=$jscomp.global;p=p.split(".");for(y=0;y<p.length-1;y++){var v=p[y];if(!(v in r))return;r=r[v]}p=p[p.length-1];y=r[p];u=u(y);u!=y&&null!=u&&$jscomp.defineProperty(r,p,{configurable:!0,writable:!0,value:u})};
$jscomp.polyfillIsolated=function(p,u,r,y){var v=p.split(".");p=1===v.length;y=v[0];y=!p&&y in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var G=0;G<v.length-1;G++){var w=v[G];if(!(w in y))return;y=y[w]}v=v[v.length-1];r=$jscomp.IS_SYMBOL_NATIVE&&"es6"===r?y[v]:null;u=u(r);null!=u&&(p?$jscomp.defineProperty($jscomp.polyfills,v,{configurable:!0,writable:!0,value:u}):u!==r&&(void 0===$jscomp.propertyToPolyfillSymbol[v]&&($jscomp.propertyToPolyfillSymbol[v]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(v):
$jscomp.POLYFILL_PREFIX+v),$jscomp.defineProperty(y,$jscomp.propertyToPolyfillSymbol[v],{configurable:!0,writable:!0,value:u})))};$jscomp.assign=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.assign?Object.assign:function(p,u){for(var r=1;r<arguments.length;r++){var y=arguments[r];if(y)for(var v in y)$jscomp.owns(y,v)&&(p[v]=y[v])}return p};$jscomp.polyfill("Object.assign",function(p){return p||$jscomp.assign},"es6","es3");
$jscomp.arrayIteratorImpl=function(p){var u=0;return function(){return u<p.length?{done:!1,value:p[u++]}:{done:!0}}};$jscomp.arrayIterator=function(p){return{next:$jscomp.arrayIteratorImpl(p)}};$jscomp.makeIterator=function(p){var u="undefined"!=typeof Symbol&&Symbol.iterator&&p[Symbol.iterator];return u?u.call(p):$jscomp.arrayIterator(p)};
$jscomp.polyfill("Promise",function(p){function u(){this.batch_=null}function r(w){return w instanceof v?w:new v(function(A,F){A(w)})}if(p&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return p;u.prototype.asyncExecute=function(w){if(null==this.batch_){this.batch_=[];var A=this;this.asyncExecuteFunction(function(){A.executeBatch_()})}this.batch_.push(w)};
var y=$jscomp.global.setTimeout;u.prototype.asyncExecuteFunction=function(w){y(w,0)};u.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var w=this.batch_;this.batch_=[];for(var A=0;A<w.length;++A){var F=w[A];w[A]=null;try{F()}catch(M){this.asyncThrow_(M)}}}this.batch_=null};u.prototype.asyncThrow_=function(w){this.asyncExecuteFunction(function(){throw w;})};var v=function(w){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var A=this.createResolveAndReject_();
try{w(A.resolve,A.reject)}catch(F){A.reject(F)}};v.prototype.createResolveAndReject_=function(){function w(M){return function(U){F||(F=!0,M.call(A,U))}}var A=this,F=!1;return{resolve:w(this.resolveTo_),reject:w(this.reject_)}};v.prototype.resolveTo_=function(w){if(w===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(w instanceof v)this.settleSameAsPromise_(w);else{a:switch(typeof w){case "object":var A=null!=w;break a;case "function":A=!0;break a;default:A=!1}A?this.resolveToNonPromiseObj_(w):
this.fulfill_(w)}};v.prototype.resolveToNonPromiseObj_=function(w){var A=void 0;try{A=w.then}catch(F){this.reject_(F);return}"function"==typeof A?this.settleSameAsThenable_(A,w):this.fulfill_(w)};v.prototype.reject_=function(w){this.settle_(2,w)};v.prototype.fulfill_=function(w){this.settle_(1,w)};v.prototype.settle_=function(w,A){if(0!=this.state_)throw Error("Cannot settle("+w+", "+A+"): Promise already settled in state"+this.state_);this.state_=w;this.result_=A;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};v.prototype.scheduleUnhandledRejectionCheck_=function(){var w=this;y(function(){if(w.notifyUnhandledRejection_()){var A=$jscomp.global.console;"undefined"!==typeof A&&A.error(w.result_)}},1)};v.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var w=$jscomp.global.CustomEvent,A=$jscomp.global.Event,F=$jscomp.global.dispatchEvent;if("undefined"===typeof F)return!0;"function"===typeof w?w=new w("unhandledrejection",{cancelable:!0}):
"function"===typeof A?w=new A("unhandledrejection",{cancelable:!0}):(w=$jscomp.global.document.createEvent("CustomEvent"),w.initCustomEvent("unhandledrejection",!1,!0,w));w.promise=this;w.reason=this.result_;return F(w)};v.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var w=0;w<this.onSettledCallbacks_.length;++w)G.asyncExecute(this.onSettledCallbacks_[w]);this.onSettledCallbacks_=null}};var G=new u;v.prototype.settleSameAsPromise_=function(w){var A=this.createResolveAndReject_();
w.callWhenSettled_(A.resolve,A.reject)};v.prototype.settleSameAsThenable_=function(w,A){var F=this.createResolveAndReject_();try{w.call(A,F.resolve,F.reject)}catch(M){F.reject(M)}};v.prototype.then=function(w,A){function F(X,ba){return"function"==typeof X?function(pa){try{M(X(pa))}catch(ca){U(ca)}}:ba}var M,U,ya=new v(function(X,ba){M=X;U=ba});this.callWhenSettled_(F(w,M),F(A,U));return ya};v.prototype.catch=function(w){return this.then(void 0,w)};v.prototype.callWhenSettled_=function(w,A){function F(){switch(M.state_){case 1:w(M.result_);
break;case 2:A(M.result_);break;default:throw Error("Unexpected state: "+M.state_);}}var M=this;null==this.onSettledCallbacks_?G.asyncExecute(F):this.onSettledCallbacks_.push(F);this.isRejectionHandled_=!0};v.resolve=r;v.reject=function(w){return new v(function(A,F){F(w)})};v.race=function(w){return new v(function(A,F){for(var M=$jscomp.makeIterator(w),U=M.next();!U.done;U=M.next())r(U.value).callWhenSettled_(A,F)})};v.all=function(w){var A=$jscomp.makeIterator(w),F=A.next();return F.done?r([]):new v(function(M,
U){function ya(pa){return function(ca){X[pa]=ca;ba--;0==ba&&M(X)}}var X=[],ba=0;do X.push(void 0),ba++,r(F.value).callWhenSettled_(ya(X.length-1),U),F=A.next();while(!F.done)})};return v},"es6","es3");$jscomp.checkEs6ConformanceViaProxy=function(){try{var p={},u=Object.create(new $jscomp.global.Proxy(p,{get:function(r,y,v){return r==p&&"q"==y&&v==u}}));return!0===u.q}catch(r){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;
$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.checkStringArgs=function(p,u,r){if(null==p)throw new TypeError("The 'this' value for String.prototype."+r+" must not be null or undefined");if(u instanceof RegExp)throw new TypeError("First argument to String.prototype."+r+" must not be a regular expression");return p+""};
$jscomp.polyfill("String.prototype.startsWith",function(p){return p?p:function(u,r){var y=$jscomp.checkStringArgs(this,u,"startsWith");u+="";var v=y.length,G=u.length;r=Math.max(0,Math.min(r|0,y.length));for(var w=0;w<G&&r<v;)if(y[r++]!=u[w++])return!1;return w>=G}},"es6","es3");$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(p){if(p)return p;var u=function(v,G){this.$jscomp$symbol$id_=v;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:G})};u.prototype.toString=function(){return this.$jscomp$symbol$id_};var r=0,y=function(v){if(this instanceof y)throw new TypeError("Symbol is not a constructor");return new u("jscomp_symbol_"+(v||"")+"_"+r++,v)};return y},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(p){if(p)return p;p=Symbol("Symbol.iterator");for(var u="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),r=0;r<u.length;r++){var y=$jscomp.global[u[r]];"function"===typeof y&&"function"!=typeof y.prototype[p]&&$jscomp.defineProperty(y.prototype,p,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return p},"es6",
"es3");$jscomp.iteratorPrototype=function(p){p={next:p};p[Symbol.iterator]=function(){return this};return p};$jscomp.iteratorFromArray=function(p,u){p instanceof String&&(p+="");var r=0,y=!1,v={next:function(){if(!y&&r<p.length){var G=r++;return{value:u(G,p[G]),done:!1}}y=!0;return{done:!0,value:void 0}}};v[Symbol.iterator]=function(){return v};return v};$jscomp.polyfill("Array.prototype.keys",function(p){return p?p:function(){return $jscomp.iteratorFromArray(this,function(u){return u})}},"es6","es3");
$jscomp.polyfill("Object.is",function(p){return p?p:function(u,r){return u===r?0!==u||1/u===1/r:u!==u&&r!==r}},"es6","es3");$jscomp.polyfill("Array.prototype.includes",function(p){return p?p:function(u,r){var y=this;y instanceof String&&(y=String(y));var v=y.length;r=r||0;for(0>r&&(r=Math.max(r+v,0));r<v;r++){var G=y[r];if(G===u||Object.is(G,u))return!0}return!1}},"es7","es3");
$jscomp.polyfill("String.prototype.includes",function(p){return p?p:function(u,r){return-1!==$jscomp.checkStringArgs(this,u,"includes").indexOf(u,r||0)}},"es6","es3");$jscomp.polyfill("Array.prototype.values",function(p){return p?p:function(){return $jscomp.iteratorFromArray(this,function(u,r){return r})}},"es8","es3");
$jscomp.polyfill("Array.prototype.copyWithin",function(p){function u(r){r=Number(r);return Infinity===r||-Infinity===r?r:r|0}return p?p:function(r,y,v){var G=this.length;r=u(r);y=u(y);v=void 0===v?G:u(v);r=0>r?Math.max(G+r,0):Math.min(r,G);y=0>y?Math.max(G+y,0):Math.min(y,G);v=0>v?Math.max(G+v,0):Math.min(v,G);if(r<y)for(;y<v;)y in this?this[r++]=this[y++]:(delete this[r++],y++);else for(v=Math.min(v,G+y-r),r+=v-y;v>y;)--v in this?this[--r]=this[v]:delete this[--r];return this}},"es6","es3");
$jscomp.typedArrayCopyWithin=function(p){return p?p:Array.prototype.copyWithin};$jscomp.polyfill("Int8Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Uint8Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Uint8ClampedArray.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Int16Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");
$jscomp.polyfill("Uint16Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Int32Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Uint32Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Float32Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");$jscomp.polyfill("Float64Array.prototype.copyWithin",$jscomp.typedArrayCopyWithin,"es6","es5");
$jscomp.polyfill("Math.clz32",function(p){return p?p:function(u){u=Number(u)>>>0;if(0===u)return 32;var r=0;0===(u&4294901760)&&(u<<=16,r+=16);0===(u&4278190080)&&(u<<=8,r+=8);0===(u&4026531840)&&(u<<=4,r+=4);0===(u&3221225472)&&(u<<=2,r+=2);0===(u&2147483648)&&r++;return r}},"es6","es3");
var NorthstarModule=function(){var p="undefined"!==typeof document&&document.currentScript?document.currentScript.src:void 0;"undefined"!==typeof __filename&&(p=p||__filename);return function(u){function r(a){return k.locateFile?k.locateFile(a,Y):Y+a}function y(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Bb)return Bb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&
240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function v(a,b){return a?y(H,a,b):""}function G(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&1023)<<10)|h&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=
g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}function w(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function A(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&qa[c];)++c;c<<=1;if(32<c-a&&Cb)return Cb.decode(H.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=ia[a+2*d>>1];if(0==
e)break;c+=String.fromCharCode(e)}return c}function F(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);ia[b>>1]=f;b+=2}ia[b>>1]=0;return b-d}function M(a){return 2*a.length}function U(a,b){for(var c=0,d="";!(c>=b/4);){var e=q[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function ya(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;
var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var g=a.charCodeAt(++e);f=65536+((f&1023)<<10)|g&1023}q[b>>2]=f;b+=4;if(b+4>c)break}q[b>>2]=0;return b-d}function X(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function ba(a){var b=w(a)+1,c=ra(b);c&&G(a,P,c,b);return c}function pa(a){db=a;k.HEAP8=P=new Int8Array(a);k.HEAP16=ia=new Int16Array(a);k.HEAP32=q=new Int32Array(a);k.HEAPU8=H=new Uint8Array(a);k.HEAPU16=
qa=new Uint16Array(a);k.HEAPU32=R=new Uint32Array(a);k.HEAPF32=B=new Float32Array(a);k.HEAPF64=eb=new Float64Array(a)}function ca(a){if(k.onAbort)k.onAbort(a);a="Aborted("+a+")";ja(a);Db=!0;a=new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");fb(a);throw a;}function Eb(a){try{if(a==V&&za)return new Uint8Array(za);if(gb)return gb(a);throw"both async and sync fetching of the wasm failed";}catch(b){ca(b)}}function kc(){if(!za&&(Fb||Aa)){if("function"===typeof fetch&&!V.startsWith("file://"))return fetch(V,
{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+V+"'";return a.arrayBuffer()}).catch(function(){return Eb(V)});if(hb)return new Promise(function(a,b){hb(V,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Eb(V)})}function ib(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(k);else{var c=b.func;"number"===typeof c?void 0===b.arg?sa.get(c)():sa.get(c)(b.arg):c(void 0===b.arg?null:b.arg)}}}function lc(a){this.excPtr=
a;this.ptr=a-16;this.set_type=function(b){q[this.ptr+4>>2]=b};this.get_type=function(){return q[this.ptr+4>>2]};this.set_destructor=function(b){q[this.ptr+8>>2]=b};this.get_destructor=function(){return q[this.ptr+8>>2]};this.set_refcount=function(b){q[this.ptr>>2]=b};this.set_caught=function(b){P[this.ptr+12>>0]=b?1:0};this.get_caught=function(){return 0!=P[this.ptr+12>>0]};this.set_rethrown=function(b){P[this.ptr+13>>0]=b?1:0};this.get_rethrown=function(){return 0!=P[this.ptr+13>>0]};this.init=function(b,
c){this.set_type(b);this.set_destructor(c);this.set_refcount(0);this.set_caught(!1);this.set_rethrown(!1)};this.add_ref=function(){q[this.ptr>>2]+=1};this.release_ref=function(){var b=q[this.ptr>>2];q[this.ptr>>2]=b-1;return 1===b}}function Ka(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Ba(a,b){a=Ka(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function La(a,b){var c=Ba(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}function C(a){throw new ta(a);}function J(a){for(var b="";H[a];)b+=Gb[H[a++]];return b}function jb(){for(;Ca.length;){var a=Ca.pop();a.$$.deleteScheduled=!1;a["delete"]()}}
function kb(a,b){for(void 0===b&&C("ptr should not be undefined");a.baseClass;)b=a.upcast(b),a=a.baseClass;return b}function Hb(a){a=Ib(a);var b=J(a);fa(a);return b}function Da(a,b){var c=ma[a];void 0===c&&C(b+" has unknown type "+Hb(a));return c}function Ma(a){}function Jb(a){--a.count.value;0===a.count.value&&(a.smartPtr?a.smartPtrType.rawDestructor(a.smartPtr):a.ptrType.registeredClass.rawDestructor(a.ptr))}function ua(a){if("undefined"===typeof FinalizationGroup)return ua=function(b){return b},
a;lb=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.ptr?Jb(c):console.warn("object already deleted: "+c.ptr)});ua=function(b){lb.register(b,b.$$,b.$$);return b};Ma=function(b){lb.unregister(b.$$)};return ua(a)}function Ea(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function va(a){return this.fromWireType(R[a>>2])}function Na(a){throw new Kb(a);}function S(a,b,c){function d(h){h=c(h);h.length!==a.length&&Na("Mismatched type converter count");for(var n=0;n<a.length;++n)da(a[n],
h[n])}a.forEach(function(h){Oa[h]=b});var e=Array(b.length),f=[],g=0;b.forEach(function(h,n){ma.hasOwnProperty(h)?e[n]=ma[h]:(f.push(h),wa.hasOwnProperty(h)||(wa[h]=[]),wa[h].push(function(){e[n]=ma[h];++g;g===f.length&&d(e)}))});0===f.length&&d(e)}function Pa(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}function da(a,b,c){c=void 0===c?{}:c;if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");
var d=b.name;a||C('type "'+d+'" must have a positive integer typeid pointer');if(ma.hasOwnProperty(a)){if(c.ignoreDuplicateRegistrations)return;C("Cannot register type '"+d+"' twice")}ma[a]=b;delete Oa[a];wa.hasOwnProperty(a)&&(b=wa[a],delete wa[a],b.forEach(function(e){e()}))}function mb(a){C(a.$$.ptrType.registeredClass.name+" instance already deleted")}function ka(){}function nb(a,b,c){if(void 0===a[b].overloadTable){var d=a[b];a[b]=function(){a[b].overloadTable.hasOwnProperty(arguments.length)||
C("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].overloadTable+")!");return a[b].overloadTable[arguments.length].apply(this,arguments)};a[b].overloadTable=[];a[b].overloadTable[d.argCount]=d}}function ob(a,b,c){k.hasOwnProperty(a)?((void 0===c||void 0!==k[a].overloadTable&&void 0!==k[a].overloadTable[c])&&C("Cannot register public name '"+a+"' twice"),nb(k,a,a),k.hasOwnProperty(c)&&C("Cannot register multiple overloads of a function with the same number of arguments ("+
c+")!"),k[a].overloadTable[c]=b):(k[a]=b,void 0!==c&&(k[a].numArguments=c))}function mc(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.instancePrototype=c;this.rawDestructor=d;this.baseClass=e;this.getActualType=f;this.upcast=g;this.downcast=h;this.pureVirtualFunctions=[]}function Qa(a,b,c){for(;b!==c;)b.upcast||C("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.upcast(a),b=b.baseClass;return a}function nc(a,b){if(null===b)return this.isReference&&C("null is not a valid "+
this.name),0;b.$$||C('Cannot pass "'+pb(b)+'" as a '+this.name);b.$$.ptr||C("Cannot pass deleted object as a pointer of type "+this.name);return Qa(b.$$.ptr,b.$$.ptrType.registeredClass,this.registeredClass)}function oc(a,b){if(null===b){this.isReference&&C("null is not a valid "+this.name);if(this.isSmartPointer){var c=this.rawConstructor();null!==a&&a.push(this.rawDestructor,c);return c}return 0}b.$$||C('Cannot pass "'+pb(b)+'" as a '+this.name);b.$$.ptr||C("Cannot pass deleted object as a pointer of type "+
this.name);!this.isConst&&b.$$.ptrType.isConst&&C("Cannot convert argument of type "+(b.$$.smartPtrType?b.$$.smartPtrType.name:b.$$.ptrType.name)+" to parameter type "+this.name);c=Qa(b.$$.ptr,b.$$.ptrType.registeredClass,this.registeredClass);if(this.isSmartPointer)switch(void 0===b.$$.smartPtr&&C("Passing raw pointer to smart pointer is illegal"),this.sharingPolicy){case 0:b.$$.smartPtrType===this?c=b.$$.smartPtr:C("Cannot convert argument of type "+(b.$$.smartPtrType?b.$$.smartPtrType.name:b.$$.ptrType.name)+
" to parameter type "+this.name);break;case 1:c=b.$$.smartPtr;break;case 2:if(b.$$.smartPtrType===this)c=b.$$.smartPtr;else{var d=b.clone();c=this.rawShare(c,I.toHandle(function(){d["delete"]()}));null!==a&&a.push(this.rawDestructor,c)}break;default:C("Unsupporting sharing policy")}return c}function pc(a,b){if(null===b)return this.isReference&&C("null is not a valid "+this.name),0;b.$$||C('Cannot pass "'+pb(b)+'" as a '+this.name);b.$$.ptr||C("Cannot pass deleted object as a pointer of type "+this.name);
b.$$.ptrType.isConst&&C("Cannot convert argument of type "+b.$$.ptrType.name+" to parameter type "+this.name);return Qa(b.$$.ptr,b.$$.ptrType.registeredClass,this.registeredClass)}function Lb(a,b,c){if(b===c)return a;if(void 0===c.baseClass)return null;a=Lb(a,b,c.baseClass);return null===a?null:c.downcast(a)}function qc(a,b){b=kb(a,b);return ha[b]}function Ra(a,b){b.ptrType&&b.ptr||Na("makeClassHandle requires ptr and ptrType");!!b.smartPtrType!==!!b.smartPtr&&Na("Both smartPtrType and smartPtr must be specified");
b.count={value:1};return ua(Object.create(a,{$$:{value:b}}))}function ea(a,b,c,d,e,f,g,h,n,t,x){this.name=a;this.registeredClass=b;this.isReference=c;this.isConst=d;this.isSmartPointer=e;this.pointeeType=f;this.sharingPolicy=g;this.rawGetPointee=h;this.rawConstructor=n;this.rawShare=t;this.rawDestructor=x;e||void 0!==b.baseClass?this.toWireType=oc:(this.toWireType=d?nc:pc,this.destructorFunction=null)}function Mb(a,b,c){k.hasOwnProperty(a)||Na("Replacing nonexistant public symbol");void 0!==k[a].overloadTable&&
void 0!==c?k[a].overloadTable[c]=b:(k[a]=b,k[a].argCount=c)}function rc(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=k["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=sa.get(b).apply(null,c);return d}}function L(a,b){a=J(a);var c=a.includes("j")?rc(a,b):sa.get(b);"function"!==typeof c&&C("unknown function pointer with signature "+a+": "+b);return c}function na(a,b){function c(f){e[f]||ma[f]||
(Oa[f]?Oa[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Nb(a+": "+d.map(Hb).join([", "]));}function Ob(a,b){if(!(a instanceof Function))throw new TypeError("new_ called with constructor type "+typeof a+" which is not a function");var c=Ba(a.name||"unknownFunctionName",function(){});c.prototype=a.prototype;c=new c;a=a.apply(c,b);return a instanceof Object?a:c}function Sa(a,b,c,d,e){var f=b.length;2>f&&C("argTypes array size mismatch! Must at least get return value and 'this' types!");
var g=null!==b[1]&&null!==c,h=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].destructorFunction){h=!0;break}var n="void"!==b[0].name,t="",x="";for(c=0;c<f-2;++c)t+=(0!==c?", ":"")+"arg"+c,x+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+Ka(a)+"("+t+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+(f-2)+" args!');\n}\n";h&&(a+="var destructors = [];\n");var z=h?"destructors":"null";t="throwBindingError invoker fn runDestructors retType classParam".split(" ");
d=[C,d,e,Ea,b[0],b[1]];g&&(a+="var thisWired = classParam.toWireType("+z+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+z+", arg"+c+"); // "+b[c+2].name+"\n",t.push("argType"+c),d.push(b[c+2]);g&&(x="thisWired"+(0<x.length?", ":"")+x);a+=(n?"var rv = ":"")+"invoker(fn"+(0<x.length?", ":"")+x+");\n";if(h)a+="runDestructors(destructors);\n";else for(c=g?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].destructorFunction&&(a+=f+"_dtor("+f+"); // "+
b[c].name+"\n",t.push(f+"_dtor"),d.push(b[c].destructorFunction));n&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");t.push(a+"}\n");return Ob(Function,t).apply(null,d)}function Ta(a,b){for(var c=[],d=0;d<a;d++)c.push(q[(b>>2)+d]);return c}function Pb(a,b,c){a instanceof Object||C(c+' with invalid "this": '+a);a instanceof b.registeredClass.constructor||C(c+' incompatible with "this" of type '+a.constructor.name);a.$$.ptr||C("cannot call emscripten binding method "+c+" on deleted object");
return Qa(a.$$.ptr,a.$$.ptrType.registeredClass,b.registeredClass)}function qb(a){4<a&&0===--W[a].refcount&&(W[a]=void 0,rb.push(a))}function sc(a,b,c){switch(b){case 0:return function(d){return this.fromWireType((c?P:H)[d])};case 1:return function(d){return this.fromWireType((c?ia:qa)[d>>1])};case 2:return function(d){return this.fromWireType((c?q:R)[d>>2])};default:throw new TypeError("Unknown integer type: "+a);}}function pb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===
b||"function"===b?a.toString():""+a}function tc(a,b){switch(b){case 2:return function(c){return this.fromWireType(B[c>>2])};case 3:return function(c){return this.fromWireType(eb[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function uc(a,b,c){switch(b){case 0:return c?function(d){return P[d]}:function(d){return H[d]};case 1:return c?function(d){return ia[d>>1]}:function(d){return qa[d>>1]};case 2:return c?function(d){return q[d>>2]}:function(d){return R[d>>2]};default:throw new TypeError("Unknown integer type: "+
a);}}function Qb(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=Da(q[(b>>2)+d],"parameter "+d);return c}function Ua(a){var b=vc[a];return void 0===b?J(a):b}function Rb(){return"object"===typeof globalThis?globalThis:Function("return this")()}function wc(a){var b=Va.length;Va.push(a);return b}function xc(a){var b=a.getExtension("ANGLE_instanced_arrays");if(b)return a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,
e,f)},a.drawElementsInstanced=function(c,d,e,f,g){b.drawElementsInstancedANGLE(c,d,e,f,g)},1}function yc(a){var b=a.getExtension("OES_vertex_array_object");if(b)return a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)},1}function zc(a){var b=a.getExtension("WEBGL_draw_buffers");if(b)return a.drawBuffers=function(c,
d){b.drawBuffersWEBGL(c,d)},1}function Ac(a){try{if(!a)return window;"number"===typeof a&&(a=Bc[a]||v(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?screen:"#canvas"===a?k.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}function Fa(){if(!Fa.strings){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:sb||
"./this.program"},b;for(b in tb)void 0===tb[b]?delete a[b]:a[b]=tb[b];var c=[];for(b in a)c.push(b+"="+a[b]);Fa.strings=c}return Fa.strings}function Wa(a,b,c,d){for(var e=0;e<a;e++){var f=m[c](),g=f&&l.getNewId(d);f?(f.name=g,d[g]=f):l.recordError(1282);q[b+4*e>>2]=g}}function Cc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&l.recordError(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=m.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>l.currentContext.version){l.recordError(1282);
return}d=2*(m.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>l.currentContext.version){l.recordError(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=m.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":l.recordError(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=
0;break;default:l.recordError(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:q[b+4*a>>2]=e[a];break;case 2:B[b+4*a>>2]=e[a];break;case 4:P[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){l.recordError(1280);ja("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:l.recordError(1280);ja("GL_INVALID_ENUM in glGet"+c+
"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:c=d;R[b>>2]=c;R[b+4>>2]=(c-R[b>>2])/4294967296;break;case 0:q[b>>2]=d;break;case 2:B[b>>2]=d;break;case 4:P[b>>0]=d?1:0}}else l.recordError(1281)}function ub(a){var b=w(a)+1,c=ra(b);G(a,H,c,b);return c}function Sb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Xa(a){a-=5120;return 0==a?P:1==a?H:2==a?ia:4==a?q:6==a?B:5==a||28922==a||28520==a||30779==a||30782==a?R:qa}function vb(a,
b,c,d,e,f){a=Xa(a);f=31-Math.clz32(a.BYTES_PER_ELEMENT);var g=l.unpackAlignment;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)}function O(a){var b=m.currentProgram;if(b){var c=b.uniformLocsById[a];"number"===typeof c&&(b.uniformLocsById[a]=c=m.getUniformLocation(b,b.uniformArrayNamesById[a]+(0<c?"["+c+"]":"")));return c}l.recordError(1282)}function Dc(){function a(g){return(g=g.toTimeString().match(/\(([A-Za-z ]+)\)$/))?
g[1]:"GMT"}var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var e=d.getTimezoneOffset(),f=Math.max(b,e);q[Tb()>>2]=60*f;q[Ub()>>2]=Number(b!=e);c=a(c);d=a(d);c=ba(c);d=ba(d);e<b?(q[xa()>>2]=c,q[xa()+4>>2]=d):(q[xa()>>2]=d,q[xa()+4>>2]=c)}function wb(){wb.called||(wb.called=!0,Dc())}function xb(a){function b(){if(!Ya&&(Ya=!0,k.calledRun=!0,!Db)){ib(Vb);Wb(k);if(k.onRuntimeInitialized)k.onRuntimeInitialized();if(k.postRun)for("function"==typeof k.postRun&&(k.postRun=
[k.postRun]);k.postRun.length;)Xb.unshift(k.postRun.shift());ib(Xb)}}if(!(0<oa)){if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)Yb.unshift(k.preRun.shift());ib(Yb);0<oa||(k.setStatus?(k.setStatus("Running..."),setTimeout(function(){setTimeout(function(){k.setStatus("")},1);b()},1)):b())}}u=u||{};"use strict";var k="undefined"!==typeof u?u:{},Zb=Object.assign,Wb,fb;k.ready=new Promise(function(a,b){Wb=a;fb=b});var $b=Zb({},k),sb="./this.program",Fb="object"===typeof window,
Aa="function"===typeof importScripts,ac="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,Y="",yb,Za;if(ac){Y=Aa?require("path").dirname(Y)+"/":__dirname+"/";var bc=function(){Za||(yb=require("fs"),Za=require("path"))};var cc=function(a,b){bc();a=Za.normalize(a);return yb.readFileSync(a,b?null:"utf8")};var gb=function(a){a=cc(a,!0);a.buffer||(a=new Uint8Array(a));return a};var hb=function(a,b,c){bc();a=Za.normalize(a);yb.readFile(a,function(d,e){d?
c(d):b(e.buffer)})};1<process.argv.length&&(sb=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",function(a){throw a;});k.inspect=function(){return"[Emscripten Module object]"}}else if(Fb||Aa)Aa?Y=self.location.href:"undefined"!==typeof document&&document.currentScript&&(Y=document.currentScript.src),p&&(Y=p),Y=0!==Y.indexOf("blob:")?Y.substr(0,Y.replace(/[?#].*/,"").lastIndexOf("/")+1):"",cc=function(a){var b=
new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},Aa&&(gb=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),hb=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var Ec=k.print||console.log.bind(console),ja=k.printErr||console.warn.bind(console);Zb(k,
$b);$b=null;k.thisProgram&&(sb=k.thisProgram);var za;k.wasmBinary&&(za=k.wasmBinary);"object"!==typeof WebAssembly&&ca("no native wasm support detected");var $a,Db=!1,Bb="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0,Cb="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0,db,P,H,ia,qa,q,R,B,eb,sa,Yb=[],Vb=[],Fc=[],Xb=[],oa=0,zb=null,Ga=null;k.preloadedImages={};k.preloadedAudios={};var V="northstar_api.wasm";V.startsWith("data:application/octet-stream;base64,")||(V=
r(V));var Gc={705764:function(){k.flushPendingDeletes()},705798:function(a,b,c){throw Error("Assertion failed: "+v(a)+"#"+b+": "+v(c));}},Hc=0,W=[{},{value:void 0},{value:null},{value:!0},{value:!1}],rb=[],ta=void 0,I={toValue:function(a){a||C("Cannot use deleted val. handle = "+a);return W[a].value},toHandle:function(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=rb.length?rb.pop():W.length;W[b]={refcount:1,value:a};return b}}},dc=void 0,Gb=void 0,
Ca=[],Ha=void 0,ha={},ma={},lb=!1,ab={},wa={},Oa={},Kb=void 0,bb={},ec={},Nb=void 0,vc={},Va=[],fc=[];var gc=ac?function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:function(){return performance.now()};var Ab=[],l={counter:1,buffers:[],programs:[],framebuffers:[],renderbuffers:[],textures:[],shaders:[],vaos:[],contexts:[],offscreenCanvases:{},queries:[],samplers:[],transformFeedbacks:[],syncs:[],stringCache:{},stringiCache:{},unpackAlignment:4,recordError:function(a){l.lastError||(l.lastError=
a)},getNewId:function(a){for(var b=l.counter++,c=a.length;c<b;c++)a[c]=null;return b},getSource:function(a,b,c,d){a="";for(var e=0;e<b;++e){var f=d?q[d+4*e>>2]:-1;a+=v(q[c+4*e>>2],0>f?void 0:f)}return a},createContext:function(a,b){a.getContextSafariWebGL2Fixed||(a.getContextSafariWebGL2Fixed=a.getContext,a.getContext=function(d,e){e=a.getContextSafariWebGL2Fixed(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.majorVersion?a.getContext("webgl2",b):a.getContext("webgl",
b);return c?l.registerContext(c,b):0},registerContext:function(a,b){var c=l.getNewId(l.contexts),d={handle:c,attributes:b,version:b.majorVersion,GLctx:a};a.canvas&&(a.canvas.GLctxObject=d);l.contexts[c]=d;("undefined"===typeof b.enableExtensionsByDefault||b.enableExtensionsByDefault)&&l.initExtensions(d);return c},makeContextCurrent:function(a){l.currentContext=l.contexts[a];k.ctx=m=l.currentContext&&l.currentContext.GLctx;return!(a&&!m)},getContext:function(a){return l.contexts[a]},deleteContext:function(a){l.currentContext===
l.contexts[a]&&(l.currentContext=null);"object"===typeof D&&D.removeAllHandlersOnTarget(l.contexts[a].GLctx.canvas);l.contexts[a]&&l.contexts[a].GLctx.canvas&&(l.contexts[a].GLctx.canvas.GLctxObject=void 0);l.contexts[a]=null},initExtensions:function(a){a||(a=l.currentContext);if(!a.initExtensionsDone){a.initExtensionsDone=!0;var b=a.GLctx;xc(b);yc(b);zc(b);b.dibvbi=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.mdibvbi=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.disjointTimerQueryExt=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.disjointTimerQueryExt)b.disjointTimerQueryExt=b.getExtension("EXT_disjoint_timer_query");b.multiDrawWebgl=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}},D={inEventHandler:0,removeAllEventListeners:function(){for(var a=D.eventHandlers.length-1;0<=a;--a)D._removeHandler(a);D.eventHandlers=
[];D.deferredCalls=[]},registerRemoveEventListeners:function(){D.removeEventListenersRegistered||(Fc.push(D.removeAllEventListeners),D.removeEventListenersRegistered=!0)},deferredCalls:[],deferCall:function(a,b,c){function d(g,h){if(g.length!=h.length)return!1;for(var n in g)if(g[n]!=h[n])return!1;return!0}for(var e in D.deferredCalls){var f=D.deferredCalls[e];if(f.targetFunction==a&&d(f.argsList,c))return}D.deferredCalls.push({targetFunction:a,precedence:b,argsList:c});D.deferredCalls.sort(function(g,
h){return g.precedence<h.precedence})},removeDeferredCalls:function(a){for(var b=0;b<D.deferredCalls.length;++b)D.deferredCalls[b].targetFunction==a&&(D.deferredCalls.splice(b,1),--b)},canPerformEventHandlerRequests:function(){return D.inEventHandler&&D.currentEventHandler.allowsDeferredCalls},runDeferredCalls:function(){if(D.canPerformEventHandlerRequests())for(var a=0;a<D.deferredCalls.length;++a){var b=D.deferredCalls[a];D.deferredCalls.splice(a,1);--a;b.targetFunction.apply(null,b.argsList)}},
eventHandlers:[],removeAllHandlersOnTarget:function(a,b){for(var c=0;c<D.eventHandlers.length;++c)D.eventHandlers[c].target!=a||b&&b!=D.eventHandlers[c].eventTypeString||D._removeHandler(c--)},_removeHandler:function(a){var b=D.eventHandlers[a];b.target.removeEventListener(b.eventTypeString,b.eventListenerFunc,b.useCapture);D.eventHandlers.splice(a,1)},registerOrRemoveHandler:function(a){var b=function(c){++D.inEventHandler;D.currentEventHandler=a;D.runDeferredCalls();a.handlerFunc(c);D.runDeferredCalls();
--D.inEventHandler};if(a.callbackfunc)a.eventListenerFunc=b,a.target.addEventListener(a.eventTypeString,b,a.useCapture),D.eventHandlers.push(a),D.registerRemoveEventListeners();else for(b=0;b<D.eventHandlers.length;++b)D.eventHandlers[b].target==a.target&&D.eventHandlers[b].eventTypeString==a.eventTypeString&&D._removeHandler(b--)},getNodeNameForTarget:function(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""},fullscreenEnabled:function(){return document.fullscreenEnabled||
document.webkitFullscreenEnabled}},Ic=["default","low-power","high-performance"],Bc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0],tb={},Ia={mappings:{},buffers:[null,[],[]],printChar:function(a,b){var c=Ia.buffers[a];0===b||10===b?((1===a?Ec:ja)(y(c,0)),c.length=0):c.push(b)},varargs:void 0,get:function(){Ia.varargs+=4;return q[Ia.varargs-4>>2]},getStr:function(a){return v(a)},get64:function(a,b){return a}},la=[];ta=k.BindingError=La(Error,"BindingError");k.count_emval_handles=
function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};k.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};dc=k.PureVirtualError=La(Error,"PureVirtualError");(function(){for(var a=Array(256),b=0;256>b;++b)a[b]=String.fromCharCode(b);Gb=a})();k.getInheritedInstanceCount=function(){return Object.keys(ha).length};k.getLiveInheritedInstances=function(){var a=[],b;for(b in ha)ha.hasOwnProperty(b)&&a.push(ha[b]);return a};k.flushPendingDeletes=
jb;k.setDelayFunction=function(a){Ha=a;Ca.length&&Ha&&Ha(jb)};Kb=k.InternalError=La(Error,"InternalError");ka.prototype.isAliasOf=function(a){if(!(this instanceof ka&&a instanceof ka))return!1;var b=this.$$.ptrType.registeredClass,c=this.$$.ptr,d=a.$$.ptrType.registeredClass;for(a=a.$$.ptr;b.baseClass;)c=b.upcast(c),b=b.baseClass;for(;d.baseClass;)a=d.upcast(a),d=d.baseClass;return b===d&&c===a};ka.prototype.clone=function(){this.$$.ptr||mb(this);if(this.$$.preservePointerOnDelete)return this.$$.count.value+=
1,this;var a=ua,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.$$;a=a(c.call(b,d,{$$:{value:{count:e.count,deleteScheduled:e.deleteScheduled,preservePointerOnDelete:e.preservePointerOnDelete,ptr:e.ptr,ptrType:e.ptrType,smartPtr:e.smartPtr,smartPtrType:e.smartPtrType}}}));a.$$.count.value+=1;a.$$.deleteScheduled=!1;return a};ka.prototype["delete"]=function(){this.$$.ptr||mb(this);this.$$.deleteScheduled&&!this.$$.preservePointerOnDelete&&C("Object already scheduled for deletion");Ma(this);
Jb(this.$$);this.$$.preservePointerOnDelete||(this.$$.smartPtr=void 0,this.$$.ptr=void 0)};ka.prototype.isDeleted=function(){return!this.$$.ptr};ka.prototype.deleteLater=function(){this.$$.ptr||mb(this);this.$$.deleteScheduled&&!this.$$.preservePointerOnDelete&&C("Object already scheduled for deletion");Ca.push(this);1===Ca.length&&Ha&&Ha(jb);this.$$.deleteScheduled=!0;return this};ea.prototype.getPointee=function(a){this.rawGetPointee&&(a=this.rawGetPointee(a));return a};ea.prototype.destructor=
function(a){this.rawDestructor&&this.rawDestructor(a)};ea.prototype.argPackAdvance=8;ea.prototype.readValueFromPointer=va;ea.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};ea.prototype.fromWireType=function(a){function b(){return this.isSmartPointer?Ra(this.registeredClass.instancePrototype,{ptrType:this.pointeeType,ptr:c,smartPtrType:this,smartPtr:a}):Ra(this.registeredClass.instancePrototype,{ptrType:this,ptr:a})}var c=this.getPointee(a);if(!c)return this.destructor(a),null;var d=
qc(this.registeredClass,c);if(void 0!==d){if(0===d.$$.count.value)return d.$$.ptr=c,d.$$.smartPtr=a,d.clone();d=d.clone();this.destructor(a);return d}d=this.registeredClass.getActualType(c);d=ec[d];if(!d)return b.call(this);d=this.isConst?d.constPointerType:d.pointerType;var e=Lb(c,this.registeredClass,d.registeredClass);return null===e?b.call(this):this.isSmartPointer?Ra(d.registeredClass.instancePrototype,{ptrType:d,ptr:e,smartPtrType:this,smartPtr:a}):Ra(d.registeredClass.instancePrototype,{ptrType:d,
ptr:e})};Nb=k.UnboundTypeError=La(Error,"UnboundTypeError");for(var m,Jc=new Float32Array(288),cb=0;288>cb;++cb)la[cb]=Jc.subarray(0,cb+1);k.IMVUGL={getGL:function(){return l}};k.NORTHSTAR_TRACE_CONFIGURE=function(a,b){};k.NORTHSTAR_TRACE_CONFIGURE_FOR_GOOGLE_WTF=function(){};k.NORTHSTAR_TRACE_LOG_MESSAGE=function(a,b){};k.NORTHSTAR_TRACE_MARK=function(a){};k.NORTHSTAR_TRACE_ENTER_CONTEXT=function(a){};k.NORTHSTAR_TRACE_EXIT_CONTEXT=function(){};k.NORTHSTAR_TRACE_REPORT_MEMORY_LAYOUT=function(){};
var jc={__cxa_allocate_exception:function(a){return ra(a+16)+16},__cxa_throw:function(a,b,c){(new lc(a)).init(b,c);Hc++;throw a;},_embind_create_inheriting_constructor:function(a,b,c){a=J(a);b=Da(b,"wrapper");c=I.toValue(c);var d=[].slice,e=b.registeredClass,f=e.instancePrototype,g=e.baseClass.instancePrototype,h=e.baseClass.constructor;a=Ba(a,function(){e.baseClass.pureVirtualFunctions.forEach(function(t){if(this[t]===g[t])throw new dc("Pure virtual function "+t+" must be implemented in JavaScript");
}.bind(this));Object.defineProperty(this,"__parent",{value:f});this.__construct.apply(this,d.call(arguments))});f.__construct=function(){this===f&&C("Pass correct 'this' to __construct");var t=h.implement.apply(void 0,[this].concat(d.call(arguments)));Ma(t);var x=t.$$;t.notifyOnDestruction();x.preservePointerOnDelete=!0;Object.defineProperties(this,{$$:{value:x}});ua(this);t=x.ptr;t=kb(e,t);ha.hasOwnProperty(t)?C("Tried to register registered instance: "+t):ha[t]=this};f.__destruct=function(){this===
f&&C("Pass correct 'this' to __destruct");Ma(this);var t=this.$$.ptr;t=kb(e,t);ha.hasOwnProperty(t)?delete ha[t]:C("Tried to unregister unregistered instance: "+t)};a.prototype=Object.create(f);for(var n in c)a.prototype[n]=c[n];return I.toHandle(a)},_embind_finalize_value_array:function(a){var b=ab[a];delete ab[a];var c=b.elements,d=c.length,e=c.map(function(h){return h.getterReturnType}).concat(c.map(function(h){return h.setterArgumentType})),f=b.rawConstructor,g=b.rawDestructor;S([a],e,function(h){c.forEach(function(n,
t){var x=h[t],z=n.getter,E=n.getterContext,N=h[t+d],K=n.setter,Z=n.setterContext;n.read=function(Q){return x.fromWireType(z(E,Q))};n.write=function(Q,aa){var T=[];K(Z,Q,N.toWireType(T,aa));Ea(T)}});return[{name:b.name,fromWireType:function(n){for(var t=Array(d),x=0;x<d;++x)t[x]=c[x].read(n);g(n);return t},toWireType:function(n,t){if(d!==t.length)throw new TypeError("Incorrect number of tuple elements for "+b.name+": expected="+d+", actual="+t.length);for(var x=f(),z=0;z<d;++z)c[z].write(x,t[z]);null!==
n&&n.push(g,x);return x},argPackAdvance:8,readValueFromPointer:va,destructorFunction:g}]})},_embind_finalize_value_object:function(a){var b=bb[a];delete bb[a];var c=b.rawConstructor,d=b.rawDestructor,e=b.fields,f=e.map(function(g){return g.getterReturnType}).concat(e.map(function(g){return g.setterArgumentType}));S([a],f,function(g){var h={};e.forEach(function(n,t){var x=g[t],z=n.getter,E=n.getterContext,N=g[t+e.length],K=n.setter,Z=n.setterContext;h[n.fieldName]={read:function(Q){return x.fromWireType(z(E,
Q))},write:function(Q,aa){var T=[];K(Z,Q,N.toWireType(T,aa));Ea(T)}}});return[{name:b.name,fromWireType:function(n){var t={},x;for(x in h)t[x]=h[x].read(n);d(n);return t},toWireType:function(n,t){for(var x in h)if(!(x in t))throw new TypeError('Missing field:  "'+x+'"');var z=c();for(x in h)h[x].write(z,t[x]);null!==n&&n.push(d,z);return z},argPackAdvance:8,readValueFromPointer:va,destructorFunction:d}]})},_embind_register_bigint:function(a,b,c,d,e){},_embind_register_bool:function(a,b,c,d,e){var f=
Pa(c);b=J(b);da(a,{name:b,fromWireType:function(g){return!!g},toWireType:function(g,h){return h?d:e},argPackAdvance:8,readValueFromPointer:function(g){if(1===c)var h=P;else if(2===c)h=ia;else if(4===c)h=q;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(h[g>>f])},destructorFunction:null})},_embind_register_class:function(a,b,c,d,e,f,g,h,n,t,x,z,E){x=J(x);f=L(e,f);h&&(h=L(g,h));t&&(t=L(n,t));E=L(z,E);var N=Ka(x);ob(N,function(){na("Cannot construct "+x+" due to unbound types",
[d])});S([a,b,c],d?[d]:[],function(K){K=K[0];if(d){var Z=K.registeredClass;var Q=Z.instancePrototype}else Q=ka.prototype;K=Ba(N,function(){if(Object.getPrototypeOf(this)!==aa)throw new ta("Use 'new' to construct "+x);if(void 0===T.constructor_body)throw new ta(x+" has no accessible constructor");var hc=T.constructor_body[arguments.length];if(void 0===hc)throw new ta("Tried to invoke ctor of "+x+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(T.constructor_body).toString()+
") parameters instead!");return hc.apply(this,arguments)});var aa=Object.create(Q,{constructor:{value:K}});K.prototype=aa;var T=new mc(x,K,aa,E,Z,f,h,t);Z=new ea(x,T,!0,!1,!1);Q=new ea(x+"*",T,!1,!1,!1);var Ja=new ea(x+" const*",T,!1,!0,!1);ec[a]={pointerType:Q,constPointerType:Ja};Mb(N,K);return[Z,Q,Ja]})},_embind_register_class_class_function:function(a,b,c,d,e,f,g){var h=Ta(c,d);b=J(b);f=L(e,f);S([],[a],function(n){function t(){na("Cannot call "+x+" due to unbound types",h)}n=n[0];var x=n.name+
"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var z=n.registeredClass.constructor;void 0===z[b]?(t.argCount=c-1,z[b]=t):(nb(z,b,x),z[b].overloadTable[c-1]=t);S([],h,function(E){E=[E[0],null].concat(E.slice(1));E=Sa(x,E,null,f,g);void 0===z[b].overloadTable?(E.argCount=c-1,z[b]=E):z[b].overloadTable[c-1]=E;return[]});return[]})},_embind_register_class_constructor:function(a,b,c,d,e,f){0<b||ca(void 0);var g=Ta(b,c);e=L(d,e);S([],[a],function(h){h=h[0];var n="constructor "+h.name;void 0===h.registeredClass.constructor_body&&
(h.registeredClass.constructor_body=[]);if(void 0!==h.registeredClass.constructor_body[b-1])throw new ta("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+h.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");h.registeredClass.constructor_body[b-1]=function(){na("Cannot construct "+h.name+" due to unbound types",g)};S([],g,function(t){t.splice(1,0,null);h.registeredClass.constructor_body[b-1]=
Sa(n,t,null,e,f);return[]});return[]})},_embind_register_class_function:function(a,b,c,d,e,f,g,h){var n=Ta(c,d);b=J(b);f=L(e,f);S([],[a],function(t){function x(){na("Cannot call "+z+" due to unbound types",n)}t=t[0];var z=t.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&t.registeredClass.pureVirtualFunctions.push(b);var E=t.registeredClass.instancePrototype,N=E[b];void 0===N||void 0===N.overloadTable&&N.className!==t.name&&N.argCount===c-2?(x.argCount=c-2,x.className=t.name,E[b]=x):
(nb(E,b,z),E[b].overloadTable[c-2]=x);S([],n,function(K){K=Sa(z,K,t,f,g);void 0===E[b].overloadTable?(K.argCount=c-2,E[b]=K):E[b].overloadTable[c-2]=K;return[]});return[]})},_embind_register_class_property:function(a,b,c,d,e,f,g,h,n,t){b=J(b);e=L(d,e);S([],[a],function(x){x=x[0];var z=x.name+"."+b,E={get:function(){na("Cannot access "+z+" due to unbound types",[c,g])},enumerable:!0,configurable:!0};E.set=n?function(){na("Cannot access "+z+" due to unbound types",[c,g])}:function(N){C(z+" is a read-only property")};
Object.defineProperty(x.registeredClass.instancePrototype,b,E);S([],n?[c,g]:[c],function(N){var K=N[0],Z={get:function(){var aa=Pb(this,x,z+" getter");return K.fromWireType(e(f,aa))},enumerable:!0};if(n){n=L(h,n);var Q=N[1];Z.set=function(aa){var T=Pb(this,x,z+" setter"),Ja=[];n(t,T,Q.toWireType(Ja,aa));Ea(Ja)}}Object.defineProperty(x.registeredClass.instancePrototype,b,Z);return[]});return[]})},_embind_register_constant:function(a,b,c){a=J(a);S([],[b],function(d){d=d[0];k[a]=d.fromWireType(c);return[]})},
_embind_register_emval:function(a,b){b=J(b);da(a,{name:b,fromWireType:function(c){var d=I.toValue(c);qb(c);return d},toWireType:function(c,d){return I.toHandle(d)},argPackAdvance:8,readValueFromPointer:va,destructorFunction:null})},_embind_register_enum:function(a,b,c,d){function e(){}c=Pa(c);b=J(b);e.values={};da(a,{name:b,constructor:e,fromWireType:function(f){return this.constructor.values[f]},toWireType:function(f,g){return g.value},argPackAdvance:8,readValueFromPointer:sc(b,c,d),destructorFunction:null});
ob(b,e)},_embind_register_enum_value:function(a,b,c){var d=Da(a,"enum");b=J(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Ba(d.name+"_"+b,function(){})}});a.values[c]=d;a[b]=d},_embind_register_float:function(a,b,c){c=Pa(c);b=J(b);da(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){return e},argPackAdvance:8,readValueFromPointer:tc(b,c),destructorFunction:null})},_embind_register_function:function(a,b,c,d,e,f){var g=Ta(b,c);a=J(a);
e=L(d,e);ob(a,function(){na("Cannot call "+a+" due to unbound types",g)},b-1);S([],g,function(h){h=[h[0],null].concat(h.slice(1));Mb(a,Sa(a,h,null,e,f),b-1);return[]})},_embind_register_integer:function(a,b,c,d,e){b=J(b);-1===e&&(e=4294967295);e=Pa(c);var f=function(h){return h};if(0===d){var g=32-8*c;f=function(h){return h<<g>>>g}}c=b.includes("unsigned")?function(h,n){return n>>>0}:function(h,n){return n};da(a,{name:b,fromWireType:f,toWireType:c,argPackAdvance:8,readValueFromPointer:uc(b,e,0!==
d),destructorFunction:null})},_embind_register_memory_view:function(a,b,c){function d(f){f>>=2;var g=R;return new e(db,g[f+1],g[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=J(c);da(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{ignoreDuplicateRegistrations:!0})},_embind_register_smart_ptr:function(a,b,c,d,e,f,g,h,n,t,x,z){c=J(c);f=L(e,f);h=L(g,h);t=L(n,t);z=L(x,z);S([a],[b],function(E){E=E[0];return[new ea(c,E.registeredClass,
!1,!1,!0,E,d,f,h,t,z)]})},_embind_register_std_string:function(a,b){b=J(b);da(a,{name:b,fromWireType:function(c){var d,e=R[c>>2],f=Array(e);for(d=0;d<e;++d)f[d]=String.fromCharCode(H[c+4+d]);d=f.join("");fa(c);return d},toWireType:function(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"===typeof d;e||d instanceof Uint8Array||d instanceof Uint8ClampedArray||d instanceof Int8Array||C("Cannot pass non-string to std::string");var f=d.length,g=ra(4+f+1);R[g>>2]=f;if(e)for(e=0;e<f;++e){var h=
d.charCodeAt(e);255<h&&(fa(g),C("String has UTF-16 code units that do not fit in 8 bits"));H[g+4+e]=h}else for(e=0;e<f;++e)H[g+4+e]=d[e];null!==c&&c.push(fa,g);return g},argPackAdvance:8,readValueFromPointer:va,destructorFunction:function(c){fa(c)}})},_embind_register_std_wstring:function(a,b,c){c=J(c);if(2===b){var d=A;var e=F;var f=M;var g=function(){return qa};var h=1}else 4===b&&(d=U,e=ya,f=X,g=function(){return R},h=2);da(a,{name:c,fromWireType:function(n){for(var t=R[n>>2],x=g(),z,E=n+4,N=0;N<=
t;++N){var K=n+4+N*b;if(N==t||0==x[K>>h])E=d(E,K-E),void 0===z?z=E:(z+=String.fromCharCode(0),z+=E),E=K+b}fa(n);return z},toWireType:function(n,t){"string"!==typeof t&&C("Cannot pass non-string to C++ string type "+c);var x=f(t),z=ra(4+x+b);R[z>>2]=x>>h;e(t,z+4,x+b);null!==n&&n.push(fa,z);return z},argPackAdvance:8,readValueFromPointer:va,destructorFunction:function(n){fa(n)}})},_embind_register_value_array:function(a,b,c,d,e,f){ab[a]={name:J(b),rawConstructor:L(c,d),rawDestructor:L(e,f),elements:[]}},
_embind_register_value_array_element:function(a,b,c,d,e,f,g,h,n){ab[a].elements.push({getterReturnType:b,getter:L(c,d),getterContext:e,setterArgumentType:f,setter:L(g,h),setterContext:n})},_embind_register_value_object:function(a,b,c,d,e,f){bb[a]={name:J(b),rawConstructor:L(c,d),rawDestructor:L(e,f),fields:[]}},_embind_register_value_object_field:function(a,b,c,d,e,f,g,h,n,t){bb[a].fields.push({fieldName:J(b),getterReturnType:c,getter:L(d,e),getterContext:f,setterArgumentType:g,setter:L(h,n),setterContext:t})},
_embind_register_void:function(a,b){b=J(b);da(a,{isVoid:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(c,d){}})},_emval_as:function(a,b,c){a=I.toValue(a);b=Da(b,"emval::as");var d=[],e=I.toHandle(d);q[c>>2]=e;return b.toWireType(d,a)},_emval_call:function(a,b,c,d){a=I.toValue(a);c=Qb(b,c);for(var e=Array(b),f=0;f<b;++f){var g=c[f];e[f]=g.readValueFromPointer(d);d+=g.argPackAdvance}a=a.apply(void 0,e);return I.toHandle(a)},_emval_call_method:function(a,b,c,d,e){a=Va[a];b=
I.toValue(b);c=Ua(c);var f=[];q[d>>2]=I.toHandle(f);return a(b,c,f,e)},_emval_call_void_method:function(a,b,c,d){a=Va[a];b=I.toValue(b);c=Ua(c);a(b,c,null,d)},_emval_decref:qb,_emval_get_global:function(a){if(0===a)return I.toHandle(Rb());a=Ua(a);return I.toHandle(Rb()[a])},_emval_get_method_caller:function(a,b){var c=Qb(a,b),d=c[0];b=d.name+"_$"+c.slice(1).map(function(x){return x.name}).join("_")+"$";var e=fc[b];if(void 0!==e)return e;e=["retType"];for(var f=[d],g="",h=0;h<a-1;++h)g+=(0!==h?", ":
"")+"arg"+h,e.push("argType"+h),f.push(c[1+h]);var n="return function "+Ka("methodCaller_"+b)+"(handle, name, destructors, args) {\n",t=0;for(h=0;h<a-1;++h)n+="    var arg"+h+" = argType"+h+".readValueFromPointer(args"+(t?"+"+t:"")+");\n",t+=c[h+1].argPackAdvance;n+="    var rv = handle[name]("+g+");\n";for(h=0;h<a-1;++h)c[h+1].deleteObject&&(n+="    argType"+h+".deleteObject(arg"+h+");\n");d.isVoid||(n+="    return retType.toWireType(destructors, rv);\n");e.push(n+"};\n");a=Ob(Function,e).apply(null,
f);e=wc(a);return fc[b]=e},_emval_get_property:function(a,b){a=I.toValue(a);b=I.toValue(b);return I.toHandle(a[b])},_emval_incref:function(a){4<a&&(W[a].refcount+=1)},_emval_new_array:function(){return I.toHandle([])},_emval_new_cstring:function(a){return I.toHandle(Ua(a))},_emval_new_object:function(){return I.toHandle({})},_emval_run_destructors:function(a){var b=I.toValue(a);Ea(b);qb(a)},_emval_set_property:function(a,b,c){a=I.toValue(a);b=I.toValue(b);c=I.toValue(c);a[b]=c},_emval_take_value:function(a,
b){a=Da(a,"_emval_take_value");a=a.readValueFromPointer(b);return I.toHandle(a)},_emval_typeof:function(a){a=I.toValue(a);return I.toHandle(typeof a)},_gmtime_js:function(a,b){a=new Date(1E3*q[a>>2]);q[b>>2]=a.getUTCSeconds();q[b+4>>2]=a.getUTCMinutes();q[b+8>>2]=a.getUTCHours();q[b+12>>2]=a.getUTCDate();q[b+16>>2]=a.getUTCMonth();q[b+20>>2]=a.getUTCFullYear()-1900;q[b+24>>2]=a.getUTCDay();var c=Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0);a=(a.getTime()-c)/864E5|0;q[b+28>>2]=a},abort:function(){ca("")},
clock_gettime:function(a,b){if(0===a)a=Date.now();else{if(1!==a&&4!==a)return q[ic()>>2]=28,-1;a=gc()}q[b>>2]=a/1E3|0;q[b+4>>2]=a%1E3*1E6|0;return 0},emscripten_asm_const_int:function(a,b,c){Ab.length=0;var d;for(c>>=2;d=H[b++];)(d=105>d)&&c&1&&c++,Ab.push(d?eb[c++>>1]:q[c]),++c;return Gc[a].apply(null,Ab)},emscripten_cancel_animation_frame:function(a){cancelAnimationFrame(a)},emscripten_get_now:gc,emscripten_is_webgl_context_lost:function(a){return!l.contexts[a]||l.contexts[a].GLctx.isContextLost()},
emscripten_memcpy_big:function(a,b,c){H.copyWithin(a,b,b+c)},emscripten_performance_now:function(){return performance.now()},emscripten_request_animation_frame:function(a,b){return requestAnimationFrame(function(c){sa.get(a)(c,b)})},emscripten_resize_heap:function(a){var b=H.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math,f=e.min;d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);e=f.call(e,2147483648,d);a:{try{$a.grow(e-db.byteLength+
65535>>>16);pa($a.buffer);var g=1;break a}catch(h){}g=void 0}if(g)return!0}return!1},emscripten_webgl_create_context:function(a,b){b>>=2;b={alpha:!!q[b+0],depth:!!q[b+1],stencil:!!q[b+2],antialias:!!q[b+3],premultipliedAlpha:!!q[b+4],preserveDrawingBuffer:!!q[b+5],powerPreference:Ic[q[b+6]],failIfMajorPerformanceCaveat:!!q[b+7],majorVersion:q[b+8],minorVersion:q[b+9],enableExtensionsByDefault:q[b+10],explicitSwapControl:q[b+11],proxyContextToMainThread:q[b+12],renderViaOffscreenBackBuffer:q[b+13]};
"number"===typeof a&&(a=v(a));a=(a=a&&"#canvas"!==a?"undefined"!==typeof l&&l.offscreenCanvases[a]?l.offscreenCanvases[a]:Ac(a):"undefined"!==typeof l&&l.offscreenCanvases.canvas?l.offscreenCanvases.canvas:k.canvas)?b.explicitSwapControl?0:l.createContext(a,b):0;return a},emscripten_webgl_destroy_context:function(a){l.currentContext==a&&(l.currentContext=0);l.deleteContext(a)},emscripten_webgl_init_context_attributes:function(a){a>>=2;for(var b=0;14>b;++b)q[a+b]=0;q[a+0]=q[a+1]=q[a+3]=q[a+4]=q[a+
8]=q[a+10]=1},emscripten_webgl_make_context_current:function(a){return l.makeContextCurrent(a)?0:-5},environ_get:function(a,b){var c=0;Fa().forEach(function(d,e){var f=b+c;e=q[a+4*e>>2]=f;for(f=0;f<d.length;++f)P[e++>>0]=d.charCodeAt(f);P[e>>0]=0;c+=d.length+1});return 0},environ_sizes_get:function(a,b){var c=Fa();q[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});q[b>>2]=d;return 0},fd_close:function(a){return 0},fd_fdstat_get:function(a,b){a=1==a||2==a?2:ca();P[b>>0]=a;return 0},fd_seek:function(a,
b,c,d,e){},fd_write:function(a,b,c,d){for(var e=0,f=0;f<c;f++){var g=q[b>>2],h=q[b+4>>2];b+=8;for(var n=0;n<h;n++)Ia.printChar(a,H[g+n]);e+=h}q[d>>2]=e;return 0},glActiveTexture:function(a){m.activeTexture(a)},glAttachShader:function(a,b){m.attachShader(l.programs[a],l.shaders[b])},glBindAttribLocation:function(a,b,c){m.bindAttribLocation(l.programs[a],b,v(c))},glBindBuffer:function(a,b){35051==a?m.currentPixelPackBufferBinding=b:35052==a&&(m.currentPixelUnpackBufferBinding=b);m.bindBuffer(a,l.buffers[b])},
glBindFramebuffer:function(a,b){m.bindFramebuffer(a,l.framebuffers[b])},glBindTexture:function(a,b){m.bindTexture(a,l.textures[b])},glBindVertexArray:function(a){m.bindVertexArray(l.vaos[a])},glBlendFunc:function(a,b){m.blendFunc(a,b)},glBlendFuncSeparate:function(a,b,c,d){m.blendFuncSeparate(a,b,c,d)},glBufferData:function(a,b,c,d){2<=l.currentContext.version?c?m.bufferData(a,H,d,c,b):m.bufferData(a,b,d):m.bufferData(a,c?H.subarray(c,c+b):b,d)},glBufferSubData:function(a,b,c,d){2<=l.currentContext.version?
m.bufferSubData(a,b,H,d,c):m.bufferSubData(a,b,H.subarray(d,d+c))},glCheckFramebufferStatus:function(a){return m.checkFramebufferStatus(a)},glClear:function(a){m.clear(a)},glClearColor:function(a,b,c,d){m.clearColor(a,b,c,d)},glClearStencil:function(a){m.clearStencil(a)},glColorMask:function(a,b,c,d){m.colorMask(!!a,!!b,!!c,!!d)},glCompileShader:function(a){m.compileShader(l.shaders[a])},glCompressedTexImage2D:function(a,b,c,d,e,f,g,h){2<=l.currentContext.version?m.currentPixelUnpackBufferBinding?
m.compressedTexImage2D(a,b,c,d,e,f,g,h):m.compressedTexImage2D(a,b,c,d,e,f,H,h,g):m.compressedTexImage2D(a,b,c,d,e,f,h?H.subarray(h,h+g):null)},glCompressedTexSubImage2D:function(a,b,c,d,e,f,g,h,n){2<=l.currentContext.version?m.currentPixelUnpackBufferBinding?m.compressedTexSubImage2D(a,b,c,d,e,f,g,h,n):m.compressedTexSubImage2D(a,b,c,d,e,f,g,H,n,h):m.compressedTexSubImage2D(a,b,c,d,e,f,g,n?H.subarray(n,n+h):null)},glCreateProgram:function(){var a=l.getNewId(l.programs),b=m.createProgram();b.name=
a;b.maxUniformLength=b.maxAttributeLength=b.maxUniformBlockNameLength=0;b.uniformIdCounter=1;l.programs[a]=b;return a},glCreateShader:function(a){var b=l.getNewId(l.shaders);l.shaders[b]=m.createShader(a);return b},glCullFace:function(a){m.cullFace(a)},glDeleteBuffers:function(a,b){for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=l.buffers[d];e&&(m.deleteBuffer(e),e.name=0,l.buffers[d]=null,d==m.currentPixelPackBufferBinding&&(m.currentPixelPackBufferBinding=0),d==m.currentPixelUnpackBufferBinding&&(m.currentPixelUnpackBufferBinding=
0))}},glDeleteFramebuffers:function(a,b){for(var c=0;c<a;++c){var d=q[b+4*c>>2],e=l.framebuffers[d];e&&(m.deleteFramebuffer(e),e.name=0,l.framebuffers[d]=null)}},glDeleteProgram:function(a){if(a){var b=l.programs[a];b?(m.deleteProgram(b),b.name=0,l.programs[a]=null):l.recordError(1281)}},glDeleteShader:function(a){if(a){var b=l.shaders[a];b?(m.deleteShader(b),l.shaders[a]=null):l.recordError(1281)}},glDeleteTextures:function(a,b){for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=l.textures[d];e&&(m.deleteTexture(e),
e.name=0,l.textures[d]=null)}},glDeleteVertexArrays:function(a,b){for(var c=0;c<a;c++){var d=q[b+4*c>>2];m.deleteVertexArray(l.vaos[d]);l.vaos[d]=null}},glDepthFunc:function(a){m.depthFunc(a)},glDepthMask:function(a){m.depthMask(!!a)},glDisable:function(a){m.disable(a)},glDisableVertexAttribArray:function(a){m.disableVertexAttribArray(a)},glDrawElements:function(a,b,c,d){m.drawElements(a,b,c,d)},glEnable:function(a){m.enable(a)},glEnableVertexAttribArray:function(a){m.enableVertexAttribArray(a)},
glFinish:function(){m.finish()},glFramebufferTexture2D:function(a,b,c,d,e){m.framebufferTexture2D(a,b,c,l.textures[d],e)},glGenBuffers:function(a,b){Wa(a,b,"createBuffer",l.buffers)},glGenFramebuffers:function(a,b){Wa(a,b,"createFramebuffer",l.framebuffers)},glGenTextures:function(a,b){Wa(a,b,"createTexture",l.textures)},glGenVertexArrays:function(a,b){Wa(a,b,"createVertexArray",l.vaos)},glGenerateMipmap:function(a){m.generateMipmap(a)},glGetActiveUniform:function(a,b,c,d,e,f,g){a=l.programs[a];if(b=
m.getActiveUniform(a,b))c=g&&G(b.name,H,g,c),d&&(q[d>>2]=c),e&&(q[e>>2]=b.size),f&&(q[f>>2]=b.type)},glGetIntegerv:function(a,b){Cc(a,b,0)},glGetProgramInfoLog:function(a,b,c,d){a=m.getProgramInfoLog(l.programs[a]);null===a&&(a="(unknown error)");b=0<b&&d?G(a,H,d,b):0;c&&(q[c>>2]=b)},glGetProgramiv:function(a,b,c){if(c)if(a>=l.counter)l.recordError(1281);else if(a=l.programs[a],35716==b)a=m.getProgramInfoLog(a),null===a&&(a="(unknown error)"),q[c>>2]=a.length+1;else if(35719==b){if(!a.maxUniformLength)for(b=
0;b<m.getProgramParameter(a,35718);++b)a.maxUniformLength=Math.max(a.maxUniformLength,m.getActiveUniform(a,b).name.length+1);q[c>>2]=a.maxUniformLength}else if(35722==b){if(!a.maxAttributeLength)for(b=0;b<m.getProgramParameter(a,35721);++b)a.maxAttributeLength=Math.max(a.maxAttributeLength,m.getActiveAttrib(a,b).name.length+1);q[c>>2]=a.maxAttributeLength}else if(35381==b){if(!a.maxUniformBlockNameLength)for(b=0;b<m.getProgramParameter(a,35382);++b)a.maxUniformBlockNameLength=Math.max(a.maxUniformBlockNameLength,
m.getActiveUniformBlockName(a,b).length+1);q[c>>2]=a.maxUniformBlockNameLength}else q[c>>2]=m.getProgramParameter(a,b);else l.recordError(1281)},glGetShaderInfoLog:function(a,b,c,d){a=m.getShaderInfoLog(l.shaders[a]);null===a&&(a="(unknown error)");b=0<b&&d?G(a,H,d,b):0;c&&(q[c>>2]=b)},glGetShaderiv:function(a,b,c){c?35716==b?(a=m.getShaderInfoLog(l.shaders[a]),null===a&&(a="(unknown error)"),q[c>>2]=a?a.length+1:0):35720==b?(a=m.getShaderSource(l.shaders[a]),q[c>>2]=a?a.length+1:0):q[c>>2]=m.getShaderParameter(l.shaders[a],
b):l.recordError(1281)},glGetString:function(a){var b=l.stringCache[a];if(!b){switch(a){case 7939:b=m.getSupportedExtensions()||[];b=b.concat(b.map(function(c){return"GL_"+c}));b=ub(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:case 7938:case 35724:(b=m.getParameter(a))||l.recordError(1280);b=b&&ub(b);break;default:l.recordError(1280)}l.stringCache[a]=b}return b},glGetStringi:function(a,b){if(2>l.currentContext.version)return l.recordError(1282),0;var c=l.stringiCache[a];if(c)return 0>
b||b>=c.length?(l.recordError(1281),0):c[b];switch(a){case 7939:return c=m.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return ub(d)}),c=l.stringiCache[a]=c,0>b||b>=c.length?(l.recordError(1281),0):c[b];default:return l.recordError(1280),0}},glGetUniformLocation:function(a,b){b=v(b);if(a=l.programs[a]){var c=a,d=c.uniformLocsById,e=c.uniformSizeAndIdsByName,f;if(!d)for(c.uniformLocsById=d={},c.uniformArrayNamesById={},f=0;f<m.getProgramParameter(c,
35718);++f){var g=m.getActiveUniform(c,f);var h=g.name;g=g.size;var n=Sb(h);n=0<n?h.slice(0,n):h;var t=c.uniformIdCounter;c.uniformIdCounter+=g;e[n]=[g,t];for(h=0;h<g;++h)d[t]=h,c.uniformArrayNamesById[t++]=n}c=a.uniformLocsById;d=0;e=b;f=Sb(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.uniformSizeAndIdsByName[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||m.getUniformLocation(a,b)))return d}else l.recordError(1281);return-1},glLinkProgram:function(a){a=l.programs[a];m.linkProgram(a);a.uniformLocsById=
0;a.uniformSizeAndIdsByName={}},glPixelStorei:function(a,b){3317==a&&(l.unpackAlignment=b);m.pixelStorei(a,b)},glReadBuffer:function(a){m.readBuffer(a)},glReadPixels:function(a,b,c,d,e,f,g){if(2<=l.currentContext.version)if(m.currentPixelPackBufferBinding)m.readPixels(a,b,c,d,e,f,g);else{var h=Xa(f);m.readPixels(a,b,c,d,e,f,h,g>>31-Math.clz32(h.BYTES_PER_ELEMENT))}else(g=vb(f,e,c,d,g,e))?m.readPixels(a,b,c,d,e,f,g):l.recordError(1280)},glScissor:function(a,b,c,d){m.scissor(a,b,c,d)},glShaderSource:function(a,
b,c,d){b=l.getSource(a,b,c,d);m.shaderSource(l.shaders[a],b)},glTexImage2D:function(a,b,c,d,e,f,g,h,n){if(2<=l.currentContext.version)if(m.currentPixelUnpackBufferBinding)m.texImage2D(a,b,c,d,e,f,g,h,n);else if(n){var t=Xa(h);m.texImage2D(a,b,c,d,e,f,g,h,t,n>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else m.texImage2D(a,b,c,d,e,f,g,h,null);else m.texImage2D(a,b,c,d,e,f,g,h,n?vb(h,g,d,e,n,c):null)},glTexParameteri:function(a,b,c){m.texParameteri(a,b,c)},glTexSubImage2D:function(a,b,c,d,e,f,g,h,n){if(2<=
l.currentContext.version)if(m.currentPixelUnpackBufferBinding)m.texSubImage2D(a,b,c,d,e,f,g,h,n);else if(n){var t=Xa(h);m.texSubImage2D(a,b,c,d,e,f,g,h,t,n>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else m.texSubImage2D(a,b,c,d,e,f,g,h,null);else t=null,n&&(t=vb(h,g,e,f,n,0)),m.texSubImage2D(a,b,c,d,e,f,g,h,t)},glUniform1f:function(a,b){m.uniform1f(O(a),b)},glUniform1fv:function(a,b,c){if(2<=l.currentContext.version)m.uniform1fv(O(a),B,c>>2,b);else{if(288>=b)for(var d=la[b-1],e=0;e<b;++e)d[e]=B[c+4*e>>
2];else d=B.subarray(c>>2,c+4*b>>2);m.uniform1fv(O(a),d)}},glUniform1i:function(a,b){m.uniform1i(O(a),b)},glUniform2f:function(a,b,c){m.uniform2f(O(a),b,c)},glUniform2fv:function(a,b,c){if(2<=l.currentContext.version)m.uniform2fv(O(a),B,c>>2,2*b);else{if(144>=b)for(var d=la[2*b-1],e=0;e<2*b;e+=2)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2];else d=B.subarray(c>>2,c+8*b>>2);m.uniform2fv(O(a),d)}},glUniform3f:function(a,b,c,d){m.uniform3f(O(a),b,c,d)},glUniform3fv:function(a,b,c){if(2<=l.currentContext.version)m.uniform3fv(O(a),
B,c>>2,3*b);else{if(96>=b)for(var d=la[3*b-1],e=0;e<3*b;e+=3)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2],d[e+2]=B[c+(4*e+8)>>2];else d=B.subarray(c>>2,c+12*b>>2);m.uniform3fv(O(a),d)}},glUniform4f:function(a,b,c,d,e){m.uniform4f(O(a),b,c,d,e)},glUniform4fv:function(a,b,c){if(2<=l.currentContext.version)m.uniform4fv(O(a),B,c>>2,4*b);else{if(72>=b){var d=la[4*b-1],e=B;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=B.subarray(c>>2,c+16*b>>2);m.uniform4fv(O(a),
d)}},glUniformMatrix2fv:function(a,b,c,d){if(2<=l.currentContext.version)m.uniformMatrix2fv(O(a),!!c,B,d>>2,4*b);else{if(72>=b)for(var e=la[4*b-1],f=0;f<4*b;f+=4)e[f]=B[d+4*f>>2],e[f+1]=B[d+(4*f+4)>>2],e[f+2]=B[d+(4*f+8)>>2],e[f+3]=B[d+(4*f+12)>>2];else e=B.subarray(d>>2,d+16*b>>2);m.uniformMatrix2fv(O(a),!!c,e)}},glUniformMatrix3fv:function(a,b,c,d){if(2<=l.currentContext.version)m.uniformMatrix3fv(O(a),!!c,B,d>>2,9*b);else{if(32>=b)for(var e=la[9*b-1],f=0;f<9*b;f+=9)e[f]=B[d+4*f>>2],e[f+1]=B[d+
(4*f+4)>>2],e[f+2]=B[d+(4*f+8)>>2],e[f+3]=B[d+(4*f+12)>>2],e[f+4]=B[d+(4*f+16)>>2],e[f+5]=B[d+(4*f+20)>>2],e[f+6]=B[d+(4*f+24)>>2],e[f+7]=B[d+(4*f+28)>>2],e[f+8]=B[d+(4*f+32)>>2];else e=B.subarray(d>>2,d+36*b>>2);m.uniformMatrix3fv(O(a),!!c,e)}},glUniformMatrix4fv:function(a,b,c,d){if(2<=l.currentContext.version)m.uniformMatrix4fv(O(a),!!c,B,d>>2,16*b);else{if(18>=b){var e=la[16*b-1],f=B;d>>=2;for(var g=0;g<16*b;g+=16){var h=d+g;e[g]=f[h];e[g+1]=f[h+1];e[g+2]=f[h+2];e[g+3]=f[h+3];e[g+4]=f[h+4];e[g+
5]=f[h+5];e[g+6]=f[h+6];e[g+7]=f[h+7];e[g+8]=f[h+8];e[g+9]=f[h+9];e[g+10]=f[h+10];e[g+11]=f[h+11];e[g+12]=f[h+12];e[g+13]=f[h+13];e[g+14]=f[h+14];e[g+15]=f[h+15]}}else e=B.subarray(d>>2,d+64*b>>2);m.uniformMatrix4fv(O(a),!!c,e)}},glUseProgram:function(a){a=l.programs[a];m.useProgram(a);m.currentProgram=a},glVertexAttribPointer:function(a,b,c,d,e,f){m.vertexAttribPointer(a,b,c,!!d,e,f)},glViewport:function(a,b,c,d){m.viewport(a,b,c,d)},imvu_webgl_enable_extension:function(a,b){a=l.getContext(a);b=
v(b);0===b.indexOf("GL_")&&(b=b.substr(3));return a.GLctx.getExtension(b)?1:0},localtime_r:function(a,b){wb();a=new Date(1E3*q[a>>2]);q[b>>2]=a.getSeconds();q[b+4>>2]=a.getMinutes();q[b+8>>2]=a.getHours();q[b+12>>2]=a.getDate();q[b+16>>2]=a.getMonth();q[b+20>>2]=a.getFullYear()-1900;q[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1),d=(a.getTime()-c.getTime())/864E5|0;q[b+28>>2]=d;q[b+36>>2]=-(60*a.getTimezoneOffset());d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();
a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;q[b+32>>2]=a;a=q[xa()+(a?4:0)>>2];q[b+40>>2]=a;return b},setTempRet0:function(a){},time:function(a){var b=Date.now()/1E3|0;a&&(q[a>>2]=b);return b}};(function(){function a(e,f){k.asm=e.exports;$a=k.asm.memory;pa($a.buffer);sa=k.asm.__indirect_function_table;Vb.unshift(k.asm.__wasm_call_ctors);oa--;k.monitorRunDependencies&&k.monitorRunDependencies(oa);0==oa&&(null!==zb&&(clearInterval(zb),zb=null),Ga&&(e=Ga,Ga=null,e()))}function b(e){a(e.instance)}
function c(e){return kc().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){ja("failed to asynchronously prepare wasm: "+f);ca(f)})}var d={env:jc,wasi_snapshot_preview1:jc};oa++;k.monitorRunDependencies&&k.monitorRunDependencies(oa);if(k.instantiateWasm)try{return k.instantiateWasm(d,a)}catch(e){return ja("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return za||"function"!==typeof WebAssembly.instantiateStreaming||V.startsWith("data:application/octet-stream;base64,")||
V.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(V,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){ja("wasm streaming compile failed: "+f);ja("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(fb);return{}})();k.___wasm_call_ctors=function(){return(k.___wasm_call_ctors=k.asm.__wasm_call_ctors).apply(null,arguments)};var ra=k._malloc=function(){return(ra=k._malloc=k.asm.malloc).apply(null,arguments)},fa=
k._free=function(){return(fa=k._free=k.asm.free).apply(null,arguments)},ic=k.___errno_location=function(){return(ic=k.___errno_location=k.asm.__errno_location).apply(null,arguments)},Ib=k.___getTypeName=function(){return(Ib=k.___getTypeName=k.asm.__getTypeName).apply(null,arguments)};k.___embind_register_native_and_builtin_types=function(){return(k.___embind_register_native_and_builtin_types=k.asm.__embind_register_native_and_builtin_types).apply(null,arguments)};var xa=k.__get_tzname=function(){return(xa=
k.__get_tzname=k.asm._get_tzname).apply(null,arguments)},Ub=k.__get_daylight=function(){return(Ub=k.__get_daylight=k.asm._get_daylight).apply(null,arguments)},Tb=k.__get_timezone=function(){return(Tb=k.__get_timezone=k.asm._get_timezone).apply(null,arguments)};k._emscripten_main_thread_process_queued_calls=function(){return(k._emscripten_main_thread_process_queued_calls=k.asm.emscripten_main_thread_process_queued_calls).apply(null,arguments)};k.stackSave=function(){return(k.stackSave=k.asm.stackSave).apply(null,
arguments)};k.stackRestore=function(){return(k.stackRestore=k.asm.stackRestore).apply(null,arguments)};k.stackAlloc=function(){return(k.stackAlloc=k.asm.stackAlloc).apply(null,arguments)};k.dynCall_jiji=function(){return(k.dynCall_jiji=k.asm.dynCall_jiji).apply(null,arguments)};var Ya;Ga=function b(){Ya||xb();Ya||(Ga=b)};k.run=xb;if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.pop()();xb();return u.ready}}();
"object"===typeof exports&&"object"===typeof module?module.exports=NorthstarModule:"function"===typeof define&&define.amd?define([],function(){return NorthstarModule}):"object"===typeof exports&&(exports.NorthstarModule=NorthstarModule);
